      # زیپ جداگانه برای هر فایل + Smart Split
      - name: Zip each file
        run: |
          mkdir output

          PASS="${{ github.event.inputs.password }}"
          i=1

          for file in files/*; do

            [ -f "$file" ] || continue

            RAND=$(head /dev/urandom | tr -dc a-z0-9 | head -c 5)
            DATE=$(date +"%Y%m%d_%H%M%S")

            BASENAME="${RAND}_${DATE}_part${i}"

            SIZE=$(stat -c%s "$file")
            GB=$((SIZE / 1024 / 1024 / 1024))

            echo "Processing: $file"
            echo "Size: $GB GB"

            # اگر فایل بالای 2 گیگ بود
            if [ $GB -ge 2 ]; then

              echo "Large file detected -> Split ZIP 1GB"

              if [ -z "$PASS" ]; then

                zip -j -s 1g \
                  "output/${BASENAME}.zip" \
                  "$file"

              else

                zip -j -s 1g \
                  --password "$PASS" \
                  "output/${BASENAME}.zip" \
                  "$file"

              fi

            else

              echo "Normal ZIP"

              if [ -z "$PASS" ]; then

                zip -j \
                  "output/${BASENAME}.zip" \
                  "$file"

              else

                zip -j \
                  --password "$PASS" \
                  "output/${BASENAME}.zip" \
                  "$file"

              fi

            fi

            i=$((i+1))

          done
